In [ ]:
###Numpy workshop from IBM Course

In [1]:
!pip install numpy

In [10]:
import numpy as np

In [3]:
#first make list then convert to numpy array
L=[2,3,4,5,6,9]
L


[2, 3, 4, 5, 6, 9]

In [11]:
arr=np.array(L)
arr

array([2, 3, 4, 5, 6, 9])

In [12]:
#list in list and converted to array and it will show amatrix
L1=[[1,2,3,4,5,6],[9,8,7,6,5,4]]
arr1=np.array(L1)
arr1

array([[1, 2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5, 4]])

In [14]:
#for array make,  a new function called arrange function is used like range in python
arr2=np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2=np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

In [21]:
#Zero function , all the elements will be 0
arr3=np.zeros((4,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
arr4=np.zeros(6)
arr4

array([0., 0., 0., 0., 0., 0.])

In [23]:
#one function, all the elements are 1 in 2d matrix
np.ones((4,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
#making 3D matrix, where 4 is matrix no and 3 is row 5 is column
np.ones((4,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [25]:
#full function with constant no, where 5 is id no
np.full(5,10)

array([10, 10, 10, 10, 10])

In [26]:
np.full((4,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [27]:
#identity matrix, where all the diagonal will be one
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#linespace function use for  specific no  distribution of specific no in range
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [31]:
np.linspace(-1,1,10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [34]:
#logspace func use for specific no of distribution with logbase
np.logspace(0,12,7,base=2)

array([1.000e+00, 4.000e+00, 1.600e+01, 6.400e+01, 2.560e+02, 1.024e+03,
       4.096e+03])

In [36]:
#diag() function show your element inmatrix in diagonal
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [37]:
#random value generator
#like range() function in python we can generate ramdom with numpy but with rand function
np.random.rand(4)

array([0.74226115, 0.9092504 , 0.91534399, 0.40139542])

In [38]:
#for creating 2D array with random no
np.random.rand(3,4)

array([[0.99522932, 0.88486492, 0.85207453, 0.98725333],
       [0.37058956, 0.59388667, 0.23732345, 0.74401014],
       [0.32393356, 0.36849811, 0.13014851, 0.39941552]])

In [40]:
#for creating 3D array where 2 is matrix no 0 to 1
np.random.rand(2,4,5)



array([[[0.97345796, 0.43399474, 0.55609683, 0.11524614, 0.28323721],
        [0.10674743, 0.08706279, 0.09339892, 0.33743054, 0.21236089],
        [0.40026162, 0.40296985, 0.84847141, 0.53585798, 0.50829249],
        [0.54612893, 0.47751117, 0.80628779, 0.32888556, 0.22805645]],

       [[0.46872738, 0.63962684, 0.94299268, 0.09929475, 0.03332603],
        [0.16749643, 0.91718144, 0.330209  , 0.04634932, 0.4698342 ],
        [0.77551035, 0.69088237, 0.57675089, 0.80079186, 0.29743741],
        [0.54393536, 0.36623261, 0.98445891, 0.64607916, 0.14435006]]])

In [41]:
#for normal distribution no(-1 to1) we can use randn()function
np.random.randn(5)

array([ 0.13753888,  1.06338596,  0.65971361, -0.67418666,  0.77753083])

In [42]:
#for 2D
np.random.randn(5,6)


array([[-1.05667506, -0.75353422, -0.1643011 ,  0.27265039,  0.31520063,
        -2.00993152],
       [ 0.92252999,  0.79998985, -1.21291121, -0.15612056, -0.64255793,
        -0.07580432],
       [-1.1378524 ,  0.23718619,  0.59487632, -0.65479825, -0.3674681 ,
         0.80390303],
       [ 0.21768513,  0.51992024, -0.04634944, -1.19237171,  0.00454881,
        -1.68945952],
       [ 0.34004492, -0.24722342, -0.04612565, -0.79959502, -1.20282369,
         0.1864637 ]])

In [44]:
#Find the random no in range which will be integer bu randint() function
np.random.randint(0,10,10)



array([0, 0, 5, 5, 9, 3, 9, 8, 5, 6])

In [45]:
np.random.randint(0,10,2)

array([7, 6])

In [49]:
#convert array to matrix
#first define an array and reshape it
arr3=np.random.randint(0,10,10)
arr3

array([7, 2, 5, 6, 7, 4, 0, 0, 6, 0])

In [51]:
arr3.reshape(5,2)

array([[7, 2],
       [5, 6],
       [7, 4],
       [0, 0],
       [6, 0]])

In [54]:
#directly created matrix by specifying row and columnb
arr4=np.random.randint(0,10,(4,3))
arr4

array([[7, 9, 6],
       [8, 3, 7],
       [9, 3, 1],
       [9, 0, 4]])

In [56]:
#if want to different shape matrix
arr4.reshape(3,4)

array([[7, 9, 6, 8],
       [3, 7, 9, 3],
       [1, 9, 0, 4]])

In [57]:
arr4.reshape(6,2)

array([[7, 9],
       [6, 8],
       [3, 7],
       [9, 3],
       [1, 9],
       [0, 4]])

In [58]:
#max ,min determine and its index by argmin or max
arr4.max()

9

In [59]:
arr4.argmax()

1

In [60]:
arr4.argmin()

10

In [61]:
arr4.min()

0

In [62]:
#to find the dimention type
arr4.ndim

2

In [63]:
#to find the itemsize in array
arr4.itemsize

8

In [64]:
#to find the data type
arr4.dtype

dtype('int64')

In [65]:
#Numpy indexing
arr4

array([[7, 9, 6],
       [8, 3, 7],
       [9, 3, 1],
       [9, 0, 4]])

In [70]:
#find the row elemnts by indexing 
arr4[3]

array([9, 0, 4])

In [71]:
#find the both row and column elements by indexing

arr4[3,2]

4

In [74]:
column2 = arr4[:, 2]
column2

array([6, 7, 1, 4])

In [75]:
column2 = arr4[:, 1]
column2

array([9, 3, 3, 0])

In [78]:
column2[2]

3

In [80]:
column2[1]

3

In [81]:
#you can acces the data by for loop
for i in column2:
    print(i)

9
3
3
0


In [98]:
#Slicing
#first create array
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [99]:
#find first 6 elements of array
a[:6]

array([10, 11, 12, 13, 14, 15])

In [100]:
#finding last 5 element
a[5:]

array([15, 16, 17, 18, 19])

In [101]:
#assigning the elements in array
arr=a[5:]
arr

array([15, 16, 17, 18, 19])

In [103]:
#assign by specifying with slice
arr[:3]=90
arr


array([90, 90, 90, 18, 19])

In [104]:
#assign with specifying index
arr[2]=98
arr

array([90, 90, 98, 18, 19])

In [106]:
#copying the array and store in othere variable name
arr1=arr.copy()
arr1

array([90, 90, 98, 18, 19])

In [109]:
#want to see memory address
arr.data



In [108]:
arr1.data

In [111]:
#Broadcasting or assigning  1000 in whole array
arr[:]=1000
arr[:]

array([1000, 1000, 1000, 1000, 1000])

In [115]:
## Creating the "2D array and see the operation
arr2d=np.random.randint(10,110,(5,5))
arr2d
                        

array([[ 86,  84,  20,  61,  63],
       [102,  38,  20,  89,  83],
       [ 17,  80,  82,  98,  19],
       [ 94,  31,  79,  56,  72],
       [ 68,  46,  52,  53,  17]])

In [118]:
#creating 1D array with arrange () function
arr1=np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
#want to find the wlements value greater than 4, by using comparison operator
boolean= arr1>4
boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [125]:
arr1[boolean]

array([ 5,  6,  7,  8,  9, 10])

In [126]:
##Arithmatic operation between two one dimensional array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
result

array([5, 7, 9])

In [127]:
a*b

array([ 4, 10, 18])

In [128]:
a/b

array([0.25, 0.4 , 0.5 ])

In [129]:
result.max()


9

In [130]:
result.min()

5

In [131]:
#exponential
np.exp(result)

array([ 148.4131591 , 1096.63315843, 8103.08392758])

In [132]:
np.sin(result)

array([-0.95892427,  0.6569866 ,  0.41211849])

In [133]:
np.cos(result)

array([ 0.28366219,  0.75390225, -0.91113026])

In [134]:
np.tan(result)

array([-3.38051501,  0.87144798, -0.45231566])

In [135]:
np.sqrt(result)

array([2.23606798, 2.64575131, 3.        ])