In [ ]:
#Numpy workshop

In [14]:
!pip install numpy
import numpy as np

In [10]:
a = np.arange(12)
a = a.reshape(3,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [11]:
#(...)only print "o2 column # same as a[:,:,0]
a[...,0]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [12]:
#after row 1 or just a[1:]
a[1:,...]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [32]:
b=np.arange(35).reshape(5,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [19]:
b[0,0]

0

In [20]:
b[-1]

array([28, 29, 30, 31, 32, 33, 34])

In [21]:
b[1:3,2:5]

array([[ 9, 10, 11],
       [16, 17, 18]])

In [25]:
# boolean indexing
a[a<13]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
# boolean row selector
b1 = array([True,False,True,False]) 
b[b1,:]


NameError: name 'array' is not defined

In [34]:
b2 = array( [False,True,True,False,True] ) 
b[:,b2]

NameError: name 'array' is not defined

In [35]:
#The abs() function in NumPy is used to calculate the absolute value of a number or an array of numbers.
np.abs(-1)

1

In [39]:
 np.abs(array[-1.2, 1.2])

NameError: name 'array' is not defined

In [38]:
np.abs(1.2+1j)

1.5620499351813308

In [46]:
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [52]:
#cumalative sum
cumulative_sum = np.cumsum(arr)
cumulative_sum

array([ 1,  3,  6, 10, 15])

In [53]:
#cumalative multiplication
cumulative_product = np.cumprod(arr)
cumulative_product


array([  1,   2,   6,  24, 120])

In [55]:
#add() function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add the two arrays using add()
result = np.add(arr1, arr2)
result

array([5, 7, 9])

In [56]:
#all(),The all() function in NumPy is used to check whether all elements in a given array evaluate to True
arr = np.array([True, True, False])
result = np.all(arr)
result

False

In [57]:
#allclose() is a function in the NumPy library of Python that is used to compare two arrays or sequences and check if they are equalor not equal within a given tolerance. 
#The function returns True if the arrays are equal within the given tolerance, and False otherwise.

# Create two arrays to compare
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.1, 2.2, 3.3])

# Compare the arrays with a tolerance of 0.5
tolerance = 0.5
equal = np.allclose(a, b, rtol=tolerance)

# Print the result
if equal:
    print("The arrays are equal within the tolerance of", tolerance)
else:
    print("The arrays are not equal within the tolerance of", tolerance)

The arrays are equal within the tolerance of 0.5


In [58]:
#numpy.alltrue() is a function in the NumPy library of Python that returns True if all elements of an array evaluate to True, and False otherwise. 
# Create an array with some elements equal to 0
a = np.array([1, 2, 3, 0, 5])

# Check if all elements are nonzero using numpy.alltrue()
all_nonzero = np.alltrue(a)

# Print the result
if all_nonzero:
    print("All elements are nonzero.")
else:
    print("There is at least one zero element.")

There is at least one zero element.


In [60]:
#all true function also work with boolean
# Create an array with some elements equal to false
a = np.array([True, True, False, True, False])

# Check if all elements are nonzero using numpy.alltrue()
all_true = np.alltrue(a)

# Print the result
if all_true:
    print("All elements are true.")
else:
    print("There is at least one false.")



There is at least one false.


In [61]:
#numpy.angle() is a function in the NumPy library of Python that is used to compute the angle (in radians) of complex numbers. 
z = 3 + 4j

# Compute the angle of the complex number in radians using numpy.angle()
angle_rad = np.angle(z)
angle_rad

0.9272952180016122

In [62]:
z = 10+ 50j

# Compute the angle of the complex number in radians using numpy.angle()
angle_rad = np.angle(z)
angle_rad

1.373400766945016

In [63]:
#numpy.any() is a function in the NumPy library of Python that returns True if any element of an array evaluates to True, and False
# Create an array with some negative elements
a = np.array([1, 2, -3, 4, 5])

# Check if any element is negative using numpy.any()
any_negative = np.any(a < 0)

# Print the result
if any_negative:
    print("There is at least one negative element.")
else:
    print("All elements are non-negative.")

There is at least one negative element.


In [66]:
#Create a boolean array with some elements equal to True
a = np.array([False, False, True, False, True])

# Check if any element is True using numpy.any()
any_true = np.any(a)

# Print the result
if any_true:
    print("There is at least one True element.")
else:
    print("All elements are False.")

There is at least one True element.


In [67]:
#append() is a method in Python's built-in list data type that is used to add an element to the end of a list.
my_list = []

# Add elements to the list using append()
my_list.append(1)
my_list.append(2)
my_list.append(3)
my_list

[1, 2, 3]

In [68]:
#Note that append() can also be used to add a list or another iterable as a single element to the end of a list
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# Append list2 to list1 using append()
list1.append(list2)

# Print the result
print(list1)

[1, 2, 3, [4, 5, 6]]


In [72]:
#you can use the extend() method instead of append()
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# Append list2 to list1 using append()
list1.extend(list2)

# Print the result
print(list1)


[1, 2, 3, 4, 5, 6]


In [73]:
#numpy.apply_along_axis() is a function in the NumPy library of Python that applies a function along a specified axis of an array. 
# Define a function to calculate the sum of squares of a 1D array
def sum_of_squares(x):
    return np.sum(x**2)

# Create a 2D array
a = np.array([[1, 2], [3, 4]])

# Apply the function along axis 1 using numpy.apply_along_axis()
result = np.apply_along_axis(sum_of_squares, 1, a)

# Print the result
print(result)

[ 5 25]


In [74]:
# Define a function to calculate the product of elements of a 1D array
def product(x):
    return np.prod(x)

# Create a 2D array
a = np.array([[1, 2], [3, 4]])

# Apply the function along axis 0 using numpy.apply_along_axis()
result = np.apply_along_axis(product, 0, a)

# Print the result
print(result)

[3 8]


In [85]:
# Define a function to calculate the sum of elements of a 2D array
def sum_2d(x,y):
    return np.sum(x,y)

# Create a 2D array
a = np.array([[[1, 2], [3, 4]]])

# Apply the function over axis 0 using numpy.apply_over_axes()
result = np.apply_over_axes(sum_2d, a, axes=(0,1))

# Print the result
print(result)







[[[4 6]]]


In [87]:
#numpy.arange() is a function in NumPy library that returns evenly spaced values within a given interval. 
#It has a similar functionality as the Python built-in range() function, but it returns a NumPy array instead of a list.
# Create an array of values from 0 to 9 with a step of 1
a = np.arange(10)
print(a)  

# Create an array of values from 1 to 10 with a step of 1
b = np.arange(1, 11)
print(b) 
# Create an array of values from 1 to 10 with a step of 2
c = np.arange(1, 11, 2)
print(c) 



[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [88]:
# Create an array of floating-point values from 0 to 1 with a step of 0.1
d = np.arange(0, 1, 0.1)
d

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [89]:
#numpy.arccos() is a function in NumPy library that returns the inverse cosine (also known as arccosine) of a given angle in radians. 
a = np.arccos(0.5)
print(a)

1.0471975511965976


In [91]:
#numpy.arccosh() is a function in NumPy that calculates the inverse hyperbolic cosine of a given numbe
a = np.arccosh(3)
print(a)

1.762747174039086


In [92]:
#numpy.arcsin() is a function in NumPy that calculates the inverse sine of a given number. 
a = np.arcsin(0.5)
print(a)

0.5235987755982988


In [93]:
#numpy.arcsinh() is a function in NumPy that calculates the inverse hyperbolic sine of a given number.
a = np.arcsinh(2)
print(a)

1.4436354751788103


In [94]:
#numpy.arctan() is a function in NumPy that calculates the arctangent of a given number. arc=inverse
a = np.arctan(1)
print(a)

0.7853981633974483


In [95]:
#The arctanh function takes a value between -1 and 1 as input and returns the corresponding angle whose hyperbolic tangent is equal to the input value.
x = 0.5
y = np.arctanh(x)
print(y)

0.5493061443340549


In [96]:
#Unlike the arctan function, arctan2 can correctly determine the quadrant of the angle,
#The output of arctan2 is always between -π and π, even when x is negative.
#rctan2(y, x) is a function that computes the arctangent of y/x. It takes two arguments y and x which are usually the coordinates of a point in a Cartesian plane.
x = 1
y = 1
theta = np.arctan2(y, x)
print(theta)

0.7853981633974483


In [97]:
#argmax() is a function in NumPy that returns the indices of the maximum values along a given axis of a NumPy array.
a = np.array([1, 5, 2, 4, 3])
max_index = np.argmax(a)
print(max_index)

1


In [98]:
#argmin
min_index = np.argmin(a)
print(min_index)

0


In [99]:
#The argsort() function in NumPy returns the indices that would sort an array in ascending order.
a = np.array([5, 2, 8, 1, 6])
a

array([5, 2, 8, 1, 6])

In [107]:
sorted_indices = np.argsort(a)
print(sorted_indices)

[3 1 0 4 2]


In [109]:
#array()function,The array() function in NumPy creates an array from a list or tuple, by default with a data type inferred from the input data

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [110]:
## output type is specifie
b=np.array([1,2,3], dtype=complex)
b

array([1.+0.j, 2.+0.j, 3.+0.j])

In [112]:
#array(1, copy=0, subok=1, ndmin=1) creates a one-dimensional array with a single element equal to 1. 
#The copy parameter is set to 0, which means that no copy of the input data is made.
#The subok parameter is set to 1, which means that subclasses of ndarray are allowed. T
#he ndmin parameter is set to 1, which means that the output array will have at least one dimension.
c=np.array(1, copy=0, subok=1, ndmin=1)
c


array([1])

In [114]:
c=np.array(1, copy=0, subok=1, ndmin=2)
c

array([[1]])

In [115]:
## like atleast_2d but always makes a copy
c=np.array(1, subok=1, ndmin=2)
c

array([[1]])

In [116]:
#mydescriptor is a dictionary that specifies a custom data type for the record array
mydescriptor = {'names': ('gender','age','weight'), 'formats': ('S1', 'f4', 'f4')}
a = np.array([('M',64.0,75.0),('F',25.0,60.0)], dtype=mydescriptor)
a

array([(b'M', 64., 75.), (b'F', 25., 60.)],
      dtype=[('gender', 'S1'), ('age', '<f4'), ('weight', '<f4')])

In [117]:
#a.dtype.names # Access to the ordered field names
a.dtype.names 

('gender', 'age', 'weight')

In [123]:
## another way of specifying the data type
mydescriptor = [('age',np.int16),('Nchildren',np.int8),('weight',np.float32)] 

a =np.array([(64,2,75.0),(25,0,60.0)], dtype=mydescriptor)
a['Nchildren']

array([2, 0], dtype=int8)

In [125]:
## nested recarray. x, y value will be 4 byte float and nested i anj will be 2byte integer
mydescriptor = np.dtype([('x', 'f4'),('y', 'f4'),('nested', [('i', 'i2'),('j','i2')])])
t=np.array([(1.0, 2.0, (1,2))], dtype=mydescriptor)
t

array([(1., 2., (1, 2))],
      dtype=[('x', '<f4'), ('y', '<f4'), ('nested', [('i', '<i2'), ('j', '<i2')])])

In [126]:
#input 2 array
d=np.array([(1.0, 2.0, (1,2)), (2.1, 3.2, (3,2))], dtype=mydescriptor)
d

array([(1. , 2. , (1, 2)), (2.1, 3.2, (3, 2))],
      dtype=[('x', '<f4'), ('y', '<f4'), ('nested', [('i', '<i2'), ('j', '<i2')])])

In [133]:
## a plain column
y=np.array([ 1. , 2.0999999], dtype=np.float32)
y

array([1. , 2.1], dtype=float32)

In [136]:
# a plain column inside a nested column
mydescriptor = np.dtype([('x', 'f4'),('y', 'f4'),('nested', [('i', 'i2'),('j','i2')])])
c=np.array([(1.0, 2.0, (1,2))], dtype=mydescriptor)
c

array([(1., 2., (1, 2))],
      dtype=[('x', '<f4'), ('y', '<f4'), ('nested', [('i', '<i2'), ('j', '<i2')])])

In [137]:
#numpy.array_split() is a function in NumPy that splits a given array into multiple sub-arrays of equal or near-equal size. 
# Define an array with 10 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split the array into 3 sub-arrays
sub_arrays = np.array_split(arr, 3)

sub_arrays

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [139]:
#numpy.asarray() is a function that converts the input to a NumPy array
l = [1, 2, 3]

# Convert the list to a NumPy array
arr = np.asarray(l)
arr


array([1, 2, 3])

In [140]:
#asanyarray()
l = [1, 2, 3]

# Convert the list to a NumPy array
arr = np.asarray(l)
arr

array([1, 2, 3])

In [143]:
#numpy.asmatrix() is a function that converts the input to a NumPy matrix.
#Define a 2D list
lst = [[1, 2], [3, 4]]

# Convert the list to a NumPy matrix
mat = np.asmatrix(lst)
mat

matrix([[1, 2],
        [3, 4]])

In [146]:
#numpy.astype() is a method of a NumPy array that returns a new array with the same data but a different data type.
x = np.array([1,2,3])
y = x.astype(np.float64)
y
             

array([1., 2., 3.])

In [149]:
#numpy.atleast_1d() is a function that ensures that the input array has at least one dimension. 
u = 42

# Convert the scalar to a 1D array
arr = np.atleast_1d(u)
arr
arr.shape

(1,)

In [150]:
##numpy.atleast_1d() is a function that ensures that the input array has at least two dimension. 
x = np.array([1, 2, 3])
y = np.atleast_2d(x)
print(y)

[[1 2 3]]


In [151]:
#atleast_3d() is a function in NumPy, a popular Python library used for numerical computing, that is used to ensure that a given array has at least three dimensions.
x = np.array([1, 2, 3])
y = np.atleast_3d(x)
print(y)

[[[1]
  [2]
  [3]]]


In [152]:
#average() to compute the average of an array along a specified axis
a = np.array([[1, 2], [3, 4]])
average_along_axis_0 = np.average(a, axis=0)
average_along_axis_0

array([2., 3.])

In [153]:
## Beta distribution a=1, b=10
from numpy import *
from numpy.random import *
beta(a=1,b=10,size=(2,2))


array([[0.15270458, 0.02094252],
       [0.01487203, 0.12337567]])

In [154]:
#binary_repr() is a function in NumPy,  that returns a binary string representation of an integer.
num = 42
binary_string = np.binary_repr(num)
print(binary_string)

101010


In [155]:
#bincount() is a function in NumPy, 
#that counts the number of occurrences of each value in an array of non-negative integers. 
x = np.array([0, 1, 1, 3, 2, 1, 7])
counts = np.bincount(x)
print(counts)

[1 3 1 1 0 0 0 1]


In [156]:
#linspace() is a function in NumPy, 
#that returns evenly spaced numbers over a specified interval
x = np.linspace(0, 10, num=5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [157]:
x = np.linspace(0, 100, num=5)
print(x)

[  0.  25.  50.  75. 100.]


In [158]:
#unigform(),generating uniform random samples refers to generating random numbers from a continuous uniform distribution over a specified interval.
samples = np.random.uniform(low=0.0, high=1.0, size=5)
print(samples)

[0.27616268 0.8468255  0.39436959 0.1066328  0.1369489 ]


In [159]:
np.random.uniform(5,10,size = 4)

array([8.80918177, 9.51640416, 8.01055157, 5.19190073])

In [160]:
#its give value from o to 1
np.random.uniform(size = 5)

array([0.04933131, 0.13372083, 0.47629748, 0.74402915, 0.35910404])

In [161]:
#you can also made matrix by changing size 
np.random.uniform(size = (2,3))

array([[0.05211222, 0.44450489, 0.50261909],
       [0.0774317 , 0.52707482, 0.58466042]])

In [162]:
#random.randint()  
#that generates random integers within a specified range. 
#It is often used in simulations, games, and other applications where random numbers are needed.
np.random.randint(5,10,10)

array([7, 9, 8, 6, 7, 5, 9, 8, 8, 7])

In [166]:
#t generate float with random()
np.random.random(10)

array([0.97092696, 0.85760936, 0.57156864, 0.87285591, 0.12040902,
       0.87056086, 0.72394112, 0.79719142, 0.19409577, 0.83959135])

In [167]:
#logspace()used to generate a sequence of numbers that are spaced evenly on a logarithmic scale.
# Generate 5 values spaced evenly on a logarithmic scale between 1 and 10
values = np.logspace(0, 1, 5)

print(values)

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [168]:
#np.logspace() function from the NumPy library is used to generate a sequence of numbers that are spaced evenly on a logarithmic scale.
#[2^0, 2^2, 2^4, 2^8, 2^10] = [1, 4, 16, 256, 1024]
values = np.logspace(0, 10, 5,base=2)

print(values)


[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


In [169]:
#Zero()
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [170]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [171]:
#one()
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [172]:
#full() function
np.full((2,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [173]:
#identity() function
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

######Array Operations

In [174]:

#min 
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.min(arr)

1

In [175]:
#Max Return the maximum value from the array.
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.max(arr)

6

In [176]:
 #Unique
#Return an array with all the unique elements sorted
#return_index: if True, return the indices of the array.
#return_inverse: if True, return the indices of the unique array.
#return_counts: if True, return the number of times each unique element appears inside the array.
#axis: The axis to operate on. By default, the array is considered flattened.
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 1, 1, 2]))

In [177]:
#mean
np.mean(arr,dtype='int')

3

In [178]:
#Median¶
#Return the median value of the array.
np.median(arr)

3.0

In [179]:
#digitize() function is used to determine which bin a given value belongs to in a set of bins
#Return the indices of the bins to which each value in the input array belongs.
a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 3.6, 4.7, 5.3])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4])

In [180]:
#Reshape()
A = np.random.randint(15,size=(4,3))
A

array([[ 5, 14,  8],
       [ 2,  7, 14],
       [12,  4,  8],
       [14, 10, 10]])

In [181]:
A.reshape(3,4)

array([[ 5, 14,  8,  2],
       [ 7, 14, 12,  4],
       [ 8, 14, 10, 10]])

In [182]:
A.reshape(-1)

array([ 5, 14,  8,  2,  7, 14, 12,  4,  8, 14, 10, 10])

In [183]:
#Expand Dimensions,It is used to expand the dimensions of an array. 
#This method is useful for creating sample test data for testing a machine learning model.
arr = np.array([ 8, 14,  1,  8, 11,  4,  9,  4, 1, 13, 13, 11])
np.expand_dims(arr,axis=0)

array([[ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11]])

In [184]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [ 1],
       [13],
       [13],
       [11]])

In [185]:
#Squeeze,Reduce the dimension of an array by removing single-dimensional entrie
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

In [186]:
#Count Non-Zero,Count all the non-zero elements and return their count
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

In [187]:
#argwhere,Find and return all the indices of non-zero elements.
a = np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]])

In [188]:
#argmax & argmin,argmax returns the index of the max element from the array
arr = np.array([[0.12,0.64,0.19,0.05]])
np.argmax(arr)

1

In [189]:
np.argmin(min)

0

In [190]:
#Sort,Sort the array and return.
#kind: Sorting algorithm to use. {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

In [191]:
#Abs,Return the absolute values of elements inside an array
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

In [192]:
#Round,Round the float values to a specified number of decimal points.
a = np.random.random(size=(3,4))
a

array([[0.37338582, 0.29348096, 0.00880868, 0.26500329],
       [0.2086375 , 0.00938276, 0.50363064, 0.41441671],
       [0.50626341, 0.67323295, 0.89022835, 0.16932601]])

In [193]:
np.round(a,decimals=0)

array([[0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 1., 0.]])

In [194]:
np.round(a)

array([[0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 1., 0.]])

In [195]:
np.round(a,decimals=1)

array([[0.4, 0.3, 0. , 0.3],
       [0.2, 0. , 0.5, 0.4],
       [0.5, 0.7, 0.9, 0.2]])

In [197]:
#Clip,It is used to keep the values of an array within a range.
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [204]:
#np.where() is a NumPy function that returns the indices of elements in an array that satisfy a certain condition.
a = np.array([1, 6, 4, 9, 2, 8, 7])
indices = np.where(a>5)
print("Indices where a > 5: ", indices)


Indices where a > 5:  (array([1, 3, 5, 6]),)


In [205]:
# Put,Replaces specified elements of an array with given values.
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [206]:
#where [1,2]is index
np.put(arr,[1,2],[6,7])
arr

array([1, 6, 7, 4, 5, 6])

In [208]:
#Copyto,Copy the content of one array into another.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Before arr1",arr1)
print("Before arr2",arr1)
np.copyto(arr1,arr2)
print("After arr1",arr1)
print("After arr2",arr2)

Before arr1 [1 2 3]
Before arr2 [1 2 3]
After arr1 [4 5 6]
After arr2 [4 5 6]


In [ ]:
## Set operation

In [209]:
#Retrieve Common Elements
#np.intersect1d function returns all the unique values from both arrays in a sorted manner.
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([3,4,5,8,9,1])
np.intersect1d(ar1,ar2)

array([1, 3, 4, 5])

In [210]:
#return the indics of intersection  result
np.intersect1d(ar1,ar2,return_indices=True)

(array([1, 3, 4, 5]), array([0, 2, 3, 4]), array([5, 0, 1, 2]))

In [211]:
#Difference
#np.setdiff1d function returns all the unique elements from array 1 that are not present in arr2.
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 3, 4])

In [212]:
#Extracts Unique Elements From Both Arrays¶
#setxor1d function will return all the unique values from both arrays in sorted order.
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)

array([ 2,  3,  6,  9, 36])

In [216]:
#Union
#union1d function will combine both arrays into one.
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

In [ ]:
####Splitting

In [217]:
#Horizontal Split
#hsplit function will split the data horizontally into n equal parts.
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,2) 

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [218]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,4) 

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

In [222]:
#Vertical
#vsplit will split the data vertically into n equal parts.
A = np.array([[3,4,5,2],[6,7,2,6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

In [223]:
###Stacking
#Horizontal Stacking,hstack will stack appends one array at the end of another.
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

In [224]:
#Vertical Stacking,vstack will stack one array on top of another.
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [225]:
#Repeat,It is used to repeat elements of an array for n number of times.
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

In [227]:
import pandas as pd

In [228]:
fruits = pd.DataFrame([
    ['Mango',40],
    ['Apple',90],
    ['Banana',130]
],columns=['Product','ContainerSales'])
fruits
    

Product  ContainerSales
0   Mango              40
1   Apple              90
2  Banana             130

In [229]:
fruits['year'] = np.repeat(2020,fruits.shape[0])
fruits

Product  ContainerSales  year
0   Mango              40  2020
1   Apple              90  2020
2  Banana             130  2020

In [230]:
#tile,Construct an array by repeating A number of times given by reps.
np.tile("tinku",5)

array(['tinku', 'tinku', 'tinku', 'tinku', 'tinku'], dtype='<U5')

In [231]:
### Einsum,This function is used to compute many multi-dimensional and linear algebraic operations on arrays.
a = np.arange(1,10).reshape(3,3)
b = np.arange(21,30).reshape(3,3)
## ▪️ᴇxᴛʀᴀᴄᴛꜱ ᴅɪᴀɢᴏɴᴀʟꜱ
np.einsum('ii->i',a)

array([1, 5, 9])

In [232]:
#column no to row transfer
## ▪️ᴛʀᴀɴꜱᴘᴏꜱᴇ
np.einsum('ji',a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [233]:
#▪️ᴍᴀᴛʀɪx ᴍᴜʟᴛɪᴘɪᴄᴀᴛɪᴏɴ
np.einsum('ij,jk',a,b)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [234]:
##▪️ ꜱᴜᴍ ᴏꜰ ᴅɪᴀɢᴏɴᴀʟ
np.einsum('ii',a)

15

In [235]:
#Histogram,It is an important statistical analysis function of NumPy that computes histogram values for a set of data.
A = np.array([[3, 4, 5, 2],
              [6, 7, 2, 6]])
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1]),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

In [236]:
##Percentile,It computes the q-th percentile of the data along a specified axis.
a = np.array([[2, 4, 6], [4, 8, 12]])
np.percentile(a, 50)

5.0

In [237]:
# Standard Deviation and Variance
#std and var are two functions of NumPy that calculates standard deviation and variance along an axis.
a = np.array([[2, 4, 6], [4, 8, 12]])
a

array([[ 2,  4,  6],
       [ 4,  8, 12]])

In [238]:
#columnwise
np.std(a,axis=0)

array([1., 2., 3.])

In [239]:
#rowwise
np.std(a,axis=1)

array([1.63299316, 3.26598632])

In [240]:
np.var(a,axis=1)

array([ 2.66666667, 10.66666667])

In [241]:
np.var(a,axis=0)

array([1., 4., 9.])

In [243]:
#Show Floats With Two Decimal Values
np.set_printoptions(precision=2)
a = np.array([12.23456,32.34535])
print(a)

[12.23 32.35]


In [244]:
#Generate array with 500 elements '''

arr = np.linspace(10,100,500).reshape(25,20) 

##◾ 𝗦𝗮𝘃𝗲𝘀 𝗔𝗿𝗿𝗮𝘆 𝗗𝗮𝘁𝗮 𝗜𝗻𝘀𝗶𝗱𝗲 𝗮 𝘁𝘅𝘁 𝗙𝗶𝗹𝗲
np.savetxt('array.txt',arr)

In [245]:
#Load
#loadtxt used to load the content of an array from a text file.
np.loadtxt('array.txt')

array([[ 10.  ,  10.18,  10.36,  10.54,  10.72,  10.9 ,  11.08,  11.26,
         11.44,  11.62,  11.8 ,  11.98,  12.16,  12.34,  12.53,  12.71,
         12.89,  13.07,  13.25,  13.43],
       [ 13.61,  13.79,  13.97,  14.15,  14.33,  14.51,  14.69,  14.87,
         15.05,  15.23,  15.41,  15.59,  15.77,  15.95,  16.13,  16.31,
         16.49,  16.67,  16.85,  17.03],
       [ 17.21,  17.39,  17.58,  17.76,  17.94,  18.12,  18.3 ,  18.48,
         18.66,  18.84,  19.02,  19.2 ,  19.38,  19.56,  19.74,  19.92,
         20.1 ,  20.28,  20.46,  20.64],
       [ 20.82,  21.  ,  21.18,  21.36,  21.54,  21.72,  21.9 ,  22.08,
         22.26,  22.44,  22.63,  22.81,  22.99,  23.17,  23.35,  23.53,
         23.71,  23.89,  24.07,  24.25],
       [ 24.43,  24.61,  24.79,  24.97,  25.15,  25.33,  25.51,  25.69,
         25.87,  26.05,  26.23,  26.41,  26.59,  26.77,  26.95,  27.13,
         27.31,  27.49,  27.68,  27.86],
       [ 28.04,  28.22,  28.4 ,  28.58,  28.76,  28.94,  29.12,  29.3 ,
   